# 使用 Python 3.10.12 基础镜像
FROM python:3.10.12-slim

# 安装必要的构建工具（build-essential）
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# 设置工作目录
WORKDIR /app

# 复制依赖文件
COPY requirements.txt /app/

# 安装依赖
RUN pip install --no-cache-dir -r requirements.txt

# 复制应用代码
COPY . /app/

ENV CELERY_BROKER_URL=redis://redis:6379/0
ENV CELERY_RESULT_BACKEND=redis://redis:6379/0

# 给新用户分配 start_celery.sh 脚本的执行权限
RUN chmod +x /app/start_celery.sh
